### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by xpoft**
Please, add py3k support.

### CODE REVIEW

**Comment by mcdonc** [comment]
I'm afraid as a rule we don't use 2to3 for Python 3 compat, so I'm unlikely to merge this.  But I'd accept a patch that made it cross-compatible without using 2to3.

**Comment by xpoft** [comment]
Ok. Here is a patch.
And I add tox.ini - for testing in py27, py32

**Comment by mcdonc** [comment]
Amazing!  Thanks a lot.

**Comment by mcdonc** [comment]
I didn't merge the warnings stuff, but did some of it myself at https://github.com/Pylons/pyramid_deform/commit/ceeca3ab93bb803bee511b264d1efbd88a773208

**Comment by mcdonc** [comment]
By the way, can you add your name to CONTRIBUTORS.txt in a separate pull request?

**Pull request closed without merging**
