### PR TITLE
New form_options setting to configure form instance (+ more documentation)

### PR DESCRIPTION
**Pull request by davidjb**
This new dict setting (tests included) passes its contents to the form instance when being created -- allows for all options that deform.form.Form (and Field) support to be specified.

Also, additional documentation on FormView methods provided.

### CODE REVIEW

**Comment by davidjb** [comment]
Odds of this pull request being able to be merged? Thanks!

**Comment by mcdonc** [comment]
Thanks for the patch.  Nit: form_options should be specified as a tuple instead of a dict e.g. form_options = ( ('formid', 'fred'), ) instead of form_options={'formid', 'fred'}.  Rationale: mutable class-level attributes are bugs waiting to happen usually.

**Comment by davidjb** [comment]
@mcdonc Okay, I can understand that.  I'll update this accordingly.

**Comment by davidjb** [comment]
Pull request updated accordingly -- class level form_options attribute is now immutable.

**Comment by mcdonc** [comment]
Thank you!

**Pull request merged**
